version: "3.3"

services:

    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:.
        ports:
            - '8100:8100'

volumes:
    db_data:

networks:
  app-network:
    driver: bridge
  db-network: